# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerdice_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='die',
            name='name',
            field=models.CharField(default='dummy', max_length=50),
            preserve_default=False,
        ),
    ]
